config/routes.rb
Rails.application.routes.draw do
  get 'appointments/index'
  get 'appointments/new'
  root 'physicians#index'

  resources :patients
  resources :physicians do
    resources :appointments, only: [:index, :new, :create, :destroy]   
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient
  belongs_to :physician
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :physicians, through: :appointments

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/models/physician.rb
class Physician < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_physician

  def index
    @xrays = @physician.appointments.where(role: 'xray')
    @physicals = @physician.appointments.where(role: 'physicals')
    @routines = @physician.appointments.where(role: 'routines')
  end

  def show
  end

  def new
    @patients = Patient.all - @physician.patients
    @appointment = @physician.appointments.new
  end

  def create
    @appointment = @physician.appointments.new(appointment_params)
    
    if @appointment.save
      redirect_to physician_appointments_path(@physician)
    else
      render :new
    end
  end

  def destroy
    @apointment = @physician.appointments.find(params[:id])
    @appointment.destroy
    redirect_to physician_appointments_path(@physician)
  end

 private
   def set_physician
     @physician = Physician.find(params[:physician_id]) 
   end

   def appointment_params
     params.require(:appointment).permit(:role, :patient_id)
   end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :destroy]

  def index
    @patients = Patient.all
  end

  def show
  end

  def edit
  end

  def new
    @patient = Patient.new
  end

  def create 
    @patient = Patient.new(patient_params)

    if @patient.save
      redirect_to @patient
    else 
      render :new
    end 
  end

  def destroy 
    @patient.destroy
    redirect_to patients_path
  end

  private
    def set_patient 
      @patient = Patient.find(params[:id])
    end

    def patient_params 
      params.require(:patient).permit(:first_name, :last_name)
    end
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :set_physician, only: [:show, :destroy]
 
  def index
    @physicians = Physician.all
  end

  def show
  end

  def edit
  end

  def new
    @physician = Physician.new
  end

  def create
    @physician = Physician.new(physician_params)

    if @physician.save
      redirect_to @physician
    else 
      render :new
    end
  end

  def destroy
    @physician.destroy
    redirect_to physicians_path
  end

  private
    def set_physician 
      @physician = Physician.find(params[:id])
    end

    def physician_params
      params.require(:physician).permit(:name)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/appointments/index.html.erb
<h1><%= @physician.name %>: Appointments</h1>
<%= link_to 'Add Appointment', new_physician_appointment_path(@physician) %>
<hr />

<h2>Xray</h2>
<ul>
  <% @xrays.each do |xray| %>
    <li>
      <%= xray.patient.full_name %>
      <br />
      <%= link_to 'Remove', physician_appointment_path(@physician, xray), method: :delete %>
    </li>
  <% end %>
</ul>
<h2>Physical</h2>
<ul>
  <% @physicals.each do |physical| %>
    <li>
      <%= physical.patient.full_name %>
      <br />
      <%= link_to 'Remove', physician_appointment_path(@physician, physical), method: :delete %>
    </li>
 <% end %>
</ul>
<h2>Routine</h2>
<ul>
  <% @routines.each do |routine| %>
    <li>
      <%= routine.patient.full_name %>
      <br />
      <%= link_to 'Remove', physician_appointment_path(@physician, routine), method: :delete %>
   </li>
 <% end %>
</ul>

app/views/appointments/new.html.erb
<h1><%= @physician.name %> - New Appointment</h1>
<%= form_with(model: [@physician, @appointment], local: true, class: "ui form" ) do |f| %>
  <%= f.label :patient_id %>
  <%= f.select :patient_id, @patients.collect { |u| [u.full_name, u.id] } %>
  <br />
  <%= f.label :role %>
  <%= f.select :role, ['Xray', 'Physical', 'Routine'] %>
  <br />
  <%= f.submit nil, class: "ui blue button inverted" %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="ui pointing menu">
  <%= link_to "Physicians", physicians_path, class: "item" %>
  <%= link_to "Patients", patients_path, class: "item" %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doctor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <div class="ui container">
    <%= render 'layouts/navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/patients/index.html.erb
<h1>Patients</h1>
<%= link_to 'Add Patient', new_patient_path %>
<hr />
<ul>
  <% @patients.each do |patient| %>
    <li>
      <%= link_to patient.full_name, patient %>
    </li>
<% end %>
</ul>

app/views/patients/new.html.erb
<h1>Add Patient</h1>
<%= form_with(model: @patient, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true, autofocus: true, placeholder: "First Name" %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true, placeholder: "Last Name" %>
  </div>
  <%= f.submit nil, class: "ui blue button inverted" %>
<% end %>

app/views/patients/show.html.erb
<h1><%= @patient.full_name %></h1>
<hr />
<h2> Physicians <h2>
<ul>
  <% @patient.physicians.each do |patient| %>
    <li>
      <%= link_to patient.name, patient %>
    </li>
  <% end %>
</ul>
<br />
<%= link_to 'Delete Patient', @patient, method: :delete, class: "ui red button inverted" %>
<%= link_to 'Edit Patient', edit_patient_path([@physician, @patient]), class: "ui green button inverted" %>

app/views/physicians/index.html.erb
<h1>Available Physicians</h1>
<%= link_to 'Add Physician', new_physician_path %>
<hr />
<h2><%= @physicians.length <= 0 ? "No Physicians" : "" %></h2> 
<ul>
  <% @physicians.each do |physician| %>
    <li>
      <%= link_to physician.name, physician %>
    </li>
  <% end %>
</ul>

app/views/physicians/new.html.erb
<h1>Add New Physician</h1>
<%= form_with(model: @physician, local: true, class: "ui form" ) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Physician Name" %>
  </div>
  <%= f.submit nil, class: "ui blue button inverted" %>
<% end %>

app/views/physicians/show.html.erb
<h1><%= @physician.name %></h1>
<hr />
<br />
<%= link_to 'View Appointments', physician_appointments_path(@physician), class: "ui primary button inverted" %>
<%= link_to "Delete Physician", @physician, method: :delete, class: "ui red button inverted" %>